
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipbbzkzvvoejhsxiinca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwYmJ6a3p2dm9lamhzeGlpbmNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNjc3MzYsImV4cCI6MjA2MTc0MzczNn0.Acv7EvI9SY6CFFflw7aMpL_KBJDvj0YhzOmvjLbgh6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// @ts-ignore - Temporarily ignoring type issues with saved_notes table
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper type for saved notes since it's not in the auto-generated types
export interface SavedNote {
  id: string;
  user_id: string;
  note_id: string;
  created_at: string;
}
